# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'iWallpaper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iWallpaper
  pod 'SnapKit', '5.6.0'
  pod 'Alamofire', '5.8.1'
  pod 'Kingfisher', '7.10.0'
  pod 'KafkaRefresh', '1.7.0'
  pod 'FDFullscreenPopGesture', '1.1'
  pod 'MBProgressHUD', '1.2.0'

end
